#!/bin/bash
# Quick Start: Real-Time Notifications

cd /Users/keshav/Desktop/local/git/acewebx

echo "🚀 Starting Real-Time Notification System..."
echo ""
echo "IMPORTANT: You need to run 3 separate terminal windows!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "WINDOW 1: Start Reverb WebSocket Server (REQUIRED)"
echo "════════════════════════════════════════════════════════════"
echo "php artisan reverb:start"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "WINDOW 2: Start Laravel Development Server"
echo "════════════════════════════════════════════════════════════"
echo "php artisan serve"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "WINDOW 3: Build Frontend Assets"
echo "════════════════════════════════════════════════════════════"
echo "npm run build"
echo "# OR for auto-rebuild:"
echo "npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "THEN: Test the notifications"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Option A: Register new user at http://localhost:8000"
echo "Option B: Run: php test_notification.php"
echo ""
echo "✅ Check browser console (F12) for debug messages"
echo ""
